# Generated by Django 2.1.2 on 2018-11-07 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_name', models.CharField(max_length=30, verbose_name='Player name')),
                ('first_name', models.CharField(max_length=30, verbose_name='Player name')),
                ('last_name', models.CharField(max_length=30, verbose_name='Player name')),
                ('is_active', models.BooleanField()),
            ],
        ),
    ]
