# Generated by Django 2.1.2 on 2018-11-23 22:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=60, verbose_name='description')),
                ('default_points_reward', models.IntegerField()),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=60, verbose_name='Office')),
                ('description', models.CharField(max_length=60, verbose_name='description')),
            ],
        ),
        migrations.CreateModel(
            name='CategoryOffice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_points_required', models.IntegerField()),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='CategoryOfficeActivity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_points_reward', models.IntegerField()),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Office',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('office_name', models.CharField(max_length=60, verbose_name='Office')),
                ('imagen', models.CharField(max_length=350, verbose_name='imagen')),
            ],
        ),
        migrations.CreateModel(
            name='PlayerCategoryOfficeProgress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_total_points', models.IntegerField()),
                ('category_office', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='onboarding.CategoryOffice')),
            ],
        ),
        migrations.CreateModel(
            name='PlayerOfficeProgress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('player_category_office_progress', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='onboarding.PlayerCategoryOfficeProgress')),
            ],
        ),
        migrations.CreateModel(
            name='ConnectActivity',
            fields=[
                ('activity_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='onboarding.Activity')),
                ('instructions', models.CharField(max_length=300, verbose_name='instructions')),
            ],
            bases=('onboarding.activity',),
        ),
        migrations.AddField(
            model_name='categoryofficeactivity',
            name='activity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='onboarding.Activity'),
        ),
        migrations.AddField(
            model_name='categoryofficeactivity',
            name='category_office',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='onboarding.CategoryOffice'),
        ),
        migrations.AddField(
            model_name='categoryoffice',
            name='office',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='onboarding.Office'),
        ),
        migrations.AddField(
            model_name='activity',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='onboarding.Category'),
        ),
    ]
