# Generated by Django 2.1.2 on 2018-12-14 21:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0002_add_groups'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(max_length=60, verbose_name='type_name')),
            ],
        ),
        migrations.CreateModel(
            name='Briteling',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, verbose_name='briteling_name')),
                ('briteling_image', models.CharField(max_length=350, verbose_name='briteling_image')),
            ],
        ),
        migrations.RenameField(
            model_name='categoryofficeactivity',
            old_name='_points_reward',
            new_name='points_reward',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='default_points_reward',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='description',
        ),
        migrations.RemoveField(
            model_name='office',
            name='imagen',
        ),
        migrations.AddField(
            model_name='categoryoffice',
            name='category',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='onboarding.Category'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='connectactivity',
            name='solution_code',
            field=models.CharField(default=None, max_length=60, verbose_name='solution_code'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='office',
            name='office_imagen',
            field=models.CharField(default=None, max_length=350, verbose_name='office_imagen'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='playerofficeprogress',
            name='office',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='onboarding.Office'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='activity',
            name='category',
        ),
        migrations.AddField(
            model_name='activity',
            name='category',
            field=models.ManyToManyField(blank=True, to='onboarding.Category'),
        ),
        migrations.AlterField(
            model_name='category',
            name='category_name',
            field=models.CharField(max_length=60, verbose_name='category_name'),
        ),
        migrations.AlterField(
            model_name='category',
            name='description',
            field=models.CharField(max_length=350, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='categoryoffice',
            name='total_points_required',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='connectactivity',
            name='instructions',
            field=models.CharField(max_length=300, verbose_name='Activity_instructions'),
        ),
        migrations.AlterField(
            model_name='playercategoryofficeprogress',
            name='_total_points',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='playerofficeprogress',
            name='player_category_office_progress',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='onboarding.PlayerCategoryOfficeProgress'),
        ),
        migrations.AddField(
            model_name='briteling',
            name='position',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='onboarding.Office'),
        ),
        migrations.AddField(
            model_name='activity',
            name='activity_type',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='onboarding.ActivityType'),
        ),
    ]
