# Generated by Django 2.1.2 on 2018-12-20 20:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0003_auto_20181214_1844'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryOfficeActivityAttempt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('result', models.BooleanField(default=False)),
                ('category_office_activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='onboarding.CategoryOfficeActivity')),
                ('player_category_office_progress', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='onboarding.PlayerCategoryOfficeProgress')),
            ],
        ),
    ]
